server.port=8080
spring.application.name=api-gateway

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

spring.cloud.gateway.default-filters[0]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.com.spendsmart.gateway=DEBUG

springdoc.swagger-ui.path=/swagger-ui.html

springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

springdoc.swagger-ui.config-url=/v3/api-docs/swagger-config

# Disable try-it-out by default (optional ? remove this to enable it)
# springdoc.swagger-ui.supported-submit-methods=