# ?? Server ????????????????????????????????????????????
server.port=8086
spring.application.name=analytics-service

# ?? Swagger UI ????????????????????????????????????????
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# ?? Email Configuration (Gmail) ???????????????????????
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${GMAIL_USERNAME}
spring.mail.password=${GMAIL_APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ?? Scheduler ?????????????????????????????????????????
spring.task.scheduling.pool.size=5

# ?? External Service URLs ?????????????????????????????
service.expense.url=http://localhost:8083
service.income.url=http://localhost:8084
service.budget.url=http://localhost:8085
service.category.url=http://localhost:8082

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiry=86400000