# ?? Server ????????????????????????????????????????????
server.port=8086
spring.application.name=analytics-service

# ?? Swagger UI ????????????????????????????????????????
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# ?? Email Configuration (Gmail) ???????????????????????
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${GMAIL_USERNAME}
spring.mail.password=${GMAIL_APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ?? Scheduler ?????????????????????????????????????????
spring.task.scheduling.pool.size=5

# ?? External Service URLs ?????????????????????????????
service.expense.url=http://localhost:8083
service.income.url=http://localhost:8084
service.budget.url=http://localhost:8085
service.category.url=http://localhost:8082
service.auth.url=http://localhost:8081

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiry=86400000

springdoc.swagger-ui.urls[0].name=Auth Service
springdoc.swagger-ui.urls[0].url=/v3/api-docs/auth-service
springdoc.swagger-ui.urls[1].name=Expense Service
springdoc.swagger-ui.urls[1].url=/v3/api-docs/expense-service


spring.datasource.url=jdbc:mysql://localhost:3306/spendsmart_analytics?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect